#!/usr/bin/env bash

sudo apt update && sudo apt upgrade -y

sudo apt install -y \
    cinnamon-desktop-environment \
    htop \
    vim \
    mosh \
    curl \
    keepassxc \
    nextcloud-desktop \
    mumble \
    git

sudo apt remove ubuntu-session -y
sudo apt autoremove -y

sudo snap install signal-desktop wire

git clone https://github.com/basebelong/install-mint-themes

sudo bash install-mint-themes/install-mint-themes

sudo rm -rf install-mint-themes

sudo wget https://archive-media-1.nyafuu.org/wg/image/1395/08/1395089427043.png -O /usr/share/backgrounds/green.png

gsettings set org.cinnamon.desktop.background picture-uri  "file:///usr/share/backgrounds/green.png"
gsettings set org.cinnamon.desktop.interface gtk-theme Mint-Y-Darker
gsettings set org.cinnamon.theme name Mint-Y-Dark
gsettings set org.cinnamon.desktop.interface icon-theme Mint-Y-Dark
gsettings set org.cinnamon.desktop.wm.preferences theme Mint-Y-Dark

sudo reboot
